### ISSUE TITLE
Does not work from scratch

### ISSUE THREAD

**Issue by alexkutsan** [owntracks/docker-recorder#55]
Many unclear steps, and many points that just do not work. 

### How to setup eclipse-mosquitto 
Setup eclipse-mosquitto  in docker with authentification is not obvious part and should be described. 
Shortly is something like 
 1. Create ./mosquitto/{data,logs,config} dirs.
 2. Create `mosquitto.conf` without authentification
 3. Run container with mapped volumes,
 4. Jump in to the container and run `mosquitto_passwd /mosquitto/config/passwd USER`
 5. Shutdown docker, add `allow_anonymous false` and `password_file /mosquitto/config/passwd` to `mosquitto.conf`
 6. Run docker, check the connection with MQTT explorer or another way.

I had to collect this information from all over the internet, and still think that this is huge overhead just for running authenticated mqtt broker (I will definitely forget it in several month) 

### Broken and not clear docker-composes

Why https://github.com/owntracks/docker-recorder/blob/master/docker-compose.yml 
contain 2 recorders? one is built from a Docker file, and another is just a used image? 
And ports forwarded only to one of them 

Misunderstanding in ports that are used for otrecorder and mqtt (or broken compose).
8083 initially used for otrecorder web interface, but then https://github.com/owntracks/docker-recorder/blob/master/docker-compose-ssl.yml start using it for mqtt tls . 
8083 forwarded to mqtt https://github.com/owntracks/docker-recorder/blob/master/docker-compose-ssl.yml#L74 service, but at the same time recorder request nginx to forward connection to this port 
https://github.com/owntracks/docker-recorder/blob/master/docker-compose-ssl.yml#L41

### otrecorder does not listening to external connections 
I had to add `ot-recorder ${OTR_TOPIC} --http-host 0.0.0.0` in entrypoint.sh, to start listening for external connections and only after that `owntracks-frontend` works. 

### No frontend 
Easy way to check that everything works is owntracks-frontend, but this is not mentioned in this repo at all. 

### No arm messages
RPI is the most popular hardware for such things. 

### My working configuration is 

```
version: '3'

services:
  owntracks-frontend:
    container_name: owntracks-frontend
    image: alexkutsan/owntracks_frontend_arm
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - 8888:80
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    depends_on:
      - otrecorder

  otrecorder:
    build: ./docker-recorder
    ports:
      - 8083:8083
    depends_on:
      - mosquitto
    volumes:
      # - ./owntrack/config:/config
      - ./owntrack/store:/store
    restart: unless-stopped
    environment:
      OTR_HOST: mosquitto
      OTR_USER: alex
      OTR_PASS: ******************
      OTR_STORAGEDIR: /store
      
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      # - 8883:8883
    volumes:
      -  data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
```

But even within this configuration, I have to remember how to init  OTR_USER/OTR_PASS. 
And how to set up a mobile app.

**Comment by pchampio** [comment]
related issue to: https://github.com/owntracks/recorder/issues/387#issuecomment-1135660241 https://github.com/owntracks/docker-recorder/issues/54

Simple workaround:
```yaml
  otr-recorder:
    image: owntracks/recorder
    entrypoint: ot-recorder --http-host 0.0.0.0 owntracks/#
    [.....]
```
