### ISSUE TITLE
Mounts are ignored in docker compose

### ISSUE THREAD

**Issue by ippocratis** [owntracks/docker-recorder#60]
I am running owntracks-recorder with docker-compose
created some mounts for local folders on host with the container for config and store. But they are ignored and random volumes are created instead

My docker-compse.yml
```
version: '3'

services:

  otrecorder:
    container_name: ot-recorder
    image: jessestuart/owntracks
    environment:
      - OTR_PORT=0  # disables MQTT
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/media/ippo/TOSHIBA/owntracks-recorder/config:/config
      - /run/media/ippo/TOSHIBA/owntracks-recorder/store:/store
    ports:
      - 8083:8083
    restart: unless-stopped
```
The run/media/ippo/TOSHIBA/owntracks-recorder/store folder is empty

`docker inspect container_name` shows volume under "/var/lib/docker/volumes/ca799ff14564cd2f5850ff4ce8489b61dd87a71ce9220dbd699f85fa9852eef4/_data" which the recorder location data etc are stored
