### ISSUE TITLE
Path /store and /config not working with cifs mount on docker host

### ISSUE THREAD

**Issue by zutewas** [owntracks/docker-recorder#63]
Hello,

I installed owntracks/recorder on a Ubuntu 22.04.1 LTS docker host. On host I mount a cifs folder with autofs. The user who the docker image run has full access to this folder.

This is the entry in **/etc/auto.cifs-shares**
`docker -fstype=cifs,uid=1000,gid=1000,credentials=/home/user/.smbcredentials ://nas.intranet/docker`

Here the file permissions of shared folder.
```
user@virtubuntu:/media/nas/docker/otr$ ll
total 0
drwxr-xr-x 2 user user 0 Dez 16 10:20 ./
drwxr-xr-x 2 user user 0 Dez 16 10:19 ../
drwxr-xr-x 2 user user 0 Dez 16 10:20 config/
drwxr-xr-x 2 user user 0 Dez 16 10:20 store/
user@virtubuntu:/media/nas/docker/otr$
```

This compose file **do not work**

```
services:
  otrecorder:
    image: owntracks/recorder
    container_name: otrecorder
    environment:
      TZ: Europe/Berlin
    ports:
      - 8083:8083    
    restart: unless-stopped
    #volumes:
    #  - /etc/otrecorder/store:/store
    #  - /etc/otrecorder/config:/config
    volumes:
      - /media/nas/docker/otr/store:/store
      - /media/nas/docker/otr/config:/config
```

After running this I get the error:
```
Segmentation fault (core dumped)
Segmentation fault (core dumped)
```

This compose file **works**

```
services:
  otrecorder:
    image: owntracks/recorder
    container_name: otrecorder
    environment:
      TZ: Europe/Berlin
    ports:
      - 8083:8083    
    restart: unless-stopped
    volumes:
      - /etc/otrecorder/store:/store
      - /etc/otrecorder/config:/config
    #volumes:
    #  - /media/nas/docker/otr/store:/store
    #  - /media/nas/docker/otr/config:/config
```

It works if I use a local folder on the docker host.

```
user@virtubuntu:/etc/otrecorder$ ll
total 24
drwxr-xr-x   4 user user  4096 Dez 15 18:06 ./
drwxr-xr-x 152 root root 12288 Dez 16 00:19 ../
drwxrwxr-x   2 user user  4096 Dez 15 23:47 config/
drwxrwxr-x   6 user user  4096 Dez 16 10:24 store/
```

Can anybody help me ? I want to use the shared folder for better backups of all my other docker volumes. Other docker images like mosquitto, phpmyadmin, paperless, traefik ... do not have any problems with the shared cifs folder.

Thanks
