### ISSUE TITLE
Lua script causing container to not boot

### ISSUE THREAD

**Issue by sakowicz** [owntracks/docker-recorder#65]
Hello,

I want to use this [http-to-mqtt-repub.lua](https://github.com/owntracks/recorder/blob/master/contrib/lua/http-to-mqtt-repub.lua) script inside owntracks-recorder service.

My docker-compose.yml:
```yml
owntracks-recorder:
    image: owntracks/recorder
    container_name: owntracks-recorder
      - ./http-to-mqtt-repub.lua:/http-to-mqtt-repub.lua
    restart: unless-stopped
    environment:
      OTR_HOST: mqtt
      OTR_LUASCRIPT: /http-to-mqtt-repub.lua
```

This causes the container to keep a `Restarting` state.

Any ideas what I'm doing wrong? 
I can see in Dockerfile that `lua5.2-dev` is installed. 
The `http-to-mqtt-repub.lua` has 777 chmods.

What am I missing here?

**Comment by sakowicz** [comment]
Ok, I was missing JSON.lua file, so after adding:
```yml
owntracks-recorder:
    image: owntracks/recorder
    container_name: owntracks-recorder
    volumes:
      - ./http-to-mqtt-repub.lua:/http-to-mqtt-repub.lua
      - ./JSON.lua:/JSON.lua
    restart: unless-stopped
    environment:
      OTR_HOST: mqtt
      OTR_LUASCRIPT: /http-to-mqtt-repub.lua
```

[JSON.lua](https://raw.githubusercontent.com/owntracks/docker-recorder/master/JSON.lua)

And I changed this line in `http-to-mqtt-repub.lua`
```lua
JSON = (loadfile "/JSON.lua")()
```

And it works now.
