### ISSUE TITLE
Docker-compose website doesn't get populated with data

### ISSUE THREAD

**Issue by Refferic** [owntracks/docker-recorder#67]
Dear sir, madam,

I've got a question, because it doesn't matter what old solution I try to incorporate, the recorder doesn't seem to "fetch" the data from the MQTT and populate the website with the recording points.

I use Traefik2, but primarily in combination with the frontend website. Which, due to the fact that the recorder doesn't receive any data, also doesn't show any information.

Can someone point me in the right direction? The logs (in Portainer) are also empty, so that's something that I also can't utilize at the moment.

The part of my docker-compose.yml file that I use:
```
  otrecorder:
    container_name: owntracks_recorder
    image: owntracks/recorder
    entrypoint: ot-recorder --http-host 0.0.0.0 owntracks/#
    restart: unless-stopped
    ports:
      - '8083:8083'
    networks:
      - owntracks_internal
    volumes:
      - ./recorderconfig:/config
      - ./recorderstore:/store
    environment:
      - OTR_HTTPHOST=0.0.0.0
      - OTR_HOST=192.168.1.100
      - OTR_POST=1884
      - OTR_USER=xxx
      - OTR_PASS=xxx
      - OTR_STORAGEDIR=/store
    depends_on:
      - mosquitto

  mosquitto:
    container_name: owntracks_mqtt
    image: eclipse-mosquitto
    ports:
      - 1884:1884
      - 8884:8884
    networks:
      - owntracks_internal
    volumes:
      - ./mqttdata:/mosquitto/data
      - ./mqttlogs:/mosquitto/logs
      - ./mqttconfig:/mosquitto/config
    restart: unless-stopped

volumes:
  recorderstore:
  recorderconfig:
  mqttdata:
  mqttlogs:
  mqttconfig:

networks:
  owntracks_internal:
  traefik2_proxy:
    external: true

```
