### ISSUE TITLE
Error: Address not available

### ISSUE THREAD

**Issue by BLACK4585** [owntracks/docker-recorder#72]
I'm trying to set up the recorder on docker. And since the documentation is, sorry, very hard to understand, and it isn't easy to connect all services together I'm creating this issue here.
Couldn't find any documentation about this error code.
This is my compose:
```
---
version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    container_name: otrecorder
    ports:
      - 8083:8083
    volumes:
      - /owntracks/otrecorder/config:/config
      - /owntracks/otrecorder/store:/store
    restart: unless-stopped
```
