### ISSUE TITLE
starting from docker compose doesnt recognize OTR_HOST and tries to connect to localhost anyway

### ISSUE THREAD

**Issue by ozhound** [owntracks/docker-recorder#77]
As the title says. I'm trying to set this up with the docker compose example that has the manual connection for an external mqtt broker (on the same LAN) but no matter how I format it, it appears to ignore the env entry and connect to localhost anyway.

i have the following compose file. I have checked a few times and i cant see anything wrong. 

is this correct? Ive tried the ip and port with and without quotes and with and without http://

```
version: '3'

services:

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
#      - /mnt/configs/otrecorder/config:/config
      - /mnt/configs/otrecorder/storage:/store
    restart: unless-stopped
    environment:
      - OTR_HOST = "192.168.1.25"
      - OTR_PORT = "1883"
      - OTR_USER = "homeassistant"
      - OTR_PASS = "xxx"
volumes:
  store:
#  config:
```

this is the output
```

+ Skipping open defaults file /config/recorder.conf: No such file or directory
+ version 0.9.7 starting with STORAGEDIR=/store
+ connecting to MQTT on localhost:1883 as clientID ot-recorder-39bbc67f5c0e-7 without TLS
Error: Address not available
```

**Comment by ozhound** [comment]
You were right!

I was just using the exact example from the readme.md on the github page,
which, evidently is wrong

Thanks for your input

**Comment by jpmens** [comment]
Hmm, it doesn't seem to be wrong, at least [by definition](https://docs.docker.com/compose/compose-file/05-services/#environment):

> `environment` can use either an array or a map.

meaning either of the following ought to be valid (the first is the syntax you used):

```yaml
environment:
   - OTR_HOST = "192.168.1.25"
   - OTR_PORT = "1883"
```

```yaml
environment:
   OTR_HOST: "192.168.1.25"
   OTR_PORT: "1883"
```

Is this some version-specific magic? I don't know ...
