### ISSUE TITLE
[Help] How do I add Friends feature to Docker on Windows?

### ISSUE THREAD

**Issue by GitHubQueenn** [owntracks/docker-recorder#78]
Code I am using for my Docker server:

```
version: '3.5'
services:
  owntracks-recorder:
    restart: always
    image: owntracks/recorder
    volumes:
      - C:\Users\User\Desktop\OwnTracks:/store
    environment:
      OTR_PORT: 0
    ports:
      - 8083:8083
  owntracks-frontend:
    restart: always
    image: owntracks/frontend
    environment:
      SERVER_HOST: "owntracks-recorder"
      SERVER_PORT: "8083"
    ports:
      - 80:80
```

This alone gets me to have the http://localhost:8083/ page work and see my and a friend's phones connected. However, only *I* can see both phones (on my localhost page on PC) since I am hosting the server. I want us to be able to see each other's on the Friends tab. I am Android, they are iPhone. Is there an easy way to setup Friends on the recorder code above? I've tried adding:

```
          friends:
            - { tid: AA, username: me, password: 123,  devicename: phone1 }
            - { tid: BB, username: them, password: 123,  devicename: phone2 }
```
as laid out at https://owntracks.org/booklet/features/qs-config/#friends-list-syntax but when I run "docker-compose up" on the docker-compose YAML file that I added that to, I get an error saying that the "friends" property can't be used there or something. The *only* thing I have in my OwnTracks server folder is the docker-compose YAML file and then it creates the ghash, last, & rec folders when ran. When my friend connected to my server, it also made a config folder with their config in it. At the link above, it says, "Friends are basically configured like this in the 'configuration.yaml' file:" but I never had that file to begin with, just the previously-mentioned ones I just listed. Have tried researching and figuring this out for prolly 12 hours collectively now and can't figure it out. Am using HTTP mode.

Have tried the quicksetup tutorial on the site/GitHub but it's just too confusing. It mentions DNS but do I literally keep "owntracks.example.com" or no? I keep getting confused on this part. Am I supposed to have my own website or do I use "localhost" even if I am having someone remotely access it? So, the code above at least got me up-and-running and the furthest I've gotten with this. Please help.
