### ISSUE TITLE
Crashes on start if `/store` is a bind mount

### ISSUE THREAD

**Issue by romner-set** [owntracks/docker-recorder#85]
Mounting `/store` from a host dir instead of using a docker volume causes an error on start for me.

docker-compose.yml:
```yaml
services:
  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    environment:
      - OTR_PORT=0
      - OTR_HTTPHOST=0.0.0.0
    volumes:
      - /data/config:/config
      - /data/store:/store
    restart: always
```

logs:
```
otrecorder-1  | + Skipping open defaults file /config/recorder.conf: No such file or directory
otrecorder-1  | + version 0.9.8 starting with STORAGEDIR=/store
otrecorder-1  | + gcache_open: mdb_env_open: No such device
otrecorder-1  | + Can't initialize gcache in /store/ghash
```

On the host `/data` is a virtiofs mount itself, but I've also tried tmpfs to no avail.
