### ISSUE TITLE
OTR_TOPICS has no effect

### ISSUE THREAD

**Issue by Th3H0ff** [owntracks/docker-recorder#86]
Greetings
I'm trying to get owntracks-recorder to target another topic in my local MQTT and not use owntracks/#. It doesn't matter if I use OTR_TOPICS as an enviroment variable or in the recorder.conf, it simply isn't processed and recoder processes the "default" topic according to the logs.
+ Using storage at /store with precision 7
+ Configured with revgeo=true and geokey: nil
+ TZDATADB is at /config/timezone16.bin: ENOENT
+ Subscribing to owntracks/# (qos=2)

My owntracks-recorder version is 0.9.9.

My docker-compose
```
version: '3'
services:

  owntrack-backend:
    image: owntracks/recorder
    container_name: owntrack-backend
    ports:
      - 8085:8085
    volumes:
      - /home/owntrack/config:/config
      - /home/owntrack/store:/store
    restart: unless-stopped
```

My recorder.conf
```
OTR_TOPICS="msh/EU_868/2/json/#"
OTR_HTTPHOST="0.0.0.0"
OTR_HTTPPORT="8085"
OTR_HOST="172.16.80.2"
OTR_PORT="1883"
OTR_USER="***"
OTR_PASS="****"
```

Is OTR_TOPICS deprecated somehow or am I missing something else?

**Comment by jpmens** [comment]
The setting isn't deprecated and works with vanilla Recorder:

```console
$ OTR_TOPICS="msh/EU_868/2/json/#" ./ot-recorder -S JP --port 1883
Oct 30 09:20:50  ot-recorder[6149] <Debug>: version 0.9.9 starting with STORAGEDIR=JP
...
Oct 30 08:20:50  ot-recorder[6149] <Debug>: Subscribing to msh/EU_868/2/json/# (qos=2)
```

Have you changed some other setting in your configuration to verify `recorder.conf` is actually being used?

Incidentally I note you are trying to subscribe to a topic branch which does not begin with the string `owntracks/`, and while we see that works, I fear the Recorder won't do with that what you expect it to.

A good many years ago we decided the topic branch had to start with `owntracks/`, so I really don't know whether this will work for you -- I doubt it.

**Comment by jpmens** [comment]
I think the problem is due to `OTR_TOPICS` being an `ENV` configured in the `Dockerfile` and (I'm far from a specialist!) that seems to override whatever else we configure.

I've managed with the following invocation:

```console
docker run -it -p 8083:8083 \
        -e OTR_HOST=192.168.1.30 \
        -e OTR_PORT=1883 \
        -v $(pwd)/r_config:/config \
        -v $(pwd)/r_store:/store \
        --entrypoint /usr/sbin/ot-recorder \
        -e OTR_TOPICS=msh/EU_868/2/json/# \
        owntracks/recorder
```

If I don't specify `OTR_TOPICS` in the environment (`-e`), then the value in `recorder.conf` is used.

Can you adapt that to your compose situation?

**Comment by Th3H0ff** [comment]
I've been down these steps. I've updated my docker-compose to

```
  owntrack-backend:
    image: owntracks/recorder
    container_name: owntrack-backend
    ports:
      - 8085:8085
    volumes:
      - /home/owntrack/config:/config
      - /home/owntrack/store:/store
    restart: unless-stopped
    environment:
      - OTR_TOPICS = "msh/EU_868/2/json/HoffChannel/#"
```

But still the log says
+ HTTP listener started on 0.0.0.0:8083, without browser-apikey
+ HTTP prefix is unset
+ Using storage at /store with precision 7
+ Configured with revgeo=true and geokey: nil
+ TZDATADB is at /config/timezone16.bin: ENOENT
+ Subscribing to owntracks/# (qos=2)
